import { useEffect } from 'react';
import Head from 'next/head';
import Link from 'next/link';
import { useRouter } from 'next/router';
import { GetStaticProps, GetServerSideProps } from 'next';

interface Post {
  userId: number;
  id: number;
  title: string;
  body: string;
}

// export const getStaticProps: GetStaticProps = async () => {
//   const res = await fetch("https://jsonplaceholder.typicode.com/posts/2");
//   const post: Post = await res.json();
//   return {
//     props: {
//       post,
//     },
//   };
// };

export const getServerSideProps: GetServerSideProps = async () => {
  const res = await fetch('https://jsonplaceholder.typicode.com/posts/3');
  const post: Post = await res.json();
  return {
    props: {
      post,
    },
  };
};

interface HomeProps {
  post: Post;
}

export default function Home(props: HomeProps) {
  const { post } = props;
  const router = useRouter();

  useEffect(() => {
    fetch('/api/hello')
      .then((r) => r.json())
      .then(console.log);
  });
  return (
    <>
      <Head>
        <title>Re Next</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <h1>{post.title}</h1>
      <p>{post.body}</p>
      <button onClick={() => router.push('/post/456')}>Go to postId 456</button>
      <ul>
        <li>
          <Link href='/post'>切換至 pages/post/index.tsx</Link>
        </li>
        <li>
          <Link href='/post/123?q=abc'>切換至 pages/post/[postId].tsx</Link>
        </li>
        <li>
          <Link href='/post/2021/12/31'>切換至 pages/post/[...date].tsx</Link>
        </li>
        <li>
          <Link
            href={{
              pathname: '/post/[postId]',
              query: { postId: '123', q: 'abc' },
            }}
          >
            Obj 切換至 pages/post/[postId].tsx
          </Link>
        </li>
        <li>
          <Link
            href={{
              pathname: '/post/[...date]',
              query: { date: ['2021', '12', '31'] },
            }}
          >
            Obj 切換至 pages/post/[...date].tsx
          </Link>
        </li>
      </ul>
    </>
  );
}
